services:
  rubic-cube:
    container_name: rubic-cube
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    expose:
      - "80"
    restart: unless-stopped
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - npm_public
      - rubic-net

networks:
  npm_public:
    external: true
  rubic-net:
    driver: bridge
