version: '3.8'

services:
  rubic-cube:
    image: gitea.7u.pl/gkucmierz/rubic-cube:latest
    container_name: rubic-cube
    restart: always
    ports:
      - "8083:80"
    networks:
      - rubic-net

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
    restart: unless-stopped
    networks:
      - rubic-net

networks:
  rubic-net:
    driver: bridge
